project:
  output-dir: output

cite-method: natbib 

extensions:
  - quarto-journals/elsevier  

format:
  elsevier-pdf:  
    biblio-style: elsarticle-harv
    number-sections: true
    keep-tex: true
    fig-cap-location: bottom
    fig-align: center
    fig-pos: 'H'
    journal:
      name: elsarticle
      formatting: review  
      model: 3p  
    cite-style: authoryear


bibliography: bibliography.bib

execute:
  freeze: auto

editor: visual