{
  "hash": "e82db9513c3053d68af9521be781b200",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Predicting Auto Insurance Risk Using Gradient Boosting\"\nsubtitle: \"Analyzing Socio-Economic and Crash Data in New York City\"\n\nauthor:\n  - name: AJ Strauman-Scott\n    orcid: \"0009-0000-9091-0697\"\n    email: {ajstraumanscott@pm.me}\n    \n    affiliations:\n      - id: cuny\n        name: City University Of New York (CUNY)\n        department: Department of Data Science\n        city: New York City\n        country: United States of America\n        postal-code: 11212\n\nabstract: |\n  PUT AN ABSTRACT HERE!!\n\nkeywords: \n    - Gradient Boosting\n    - XGBoost\n    - SHAP explainability\n    - hyperparameter optimization\n    - auto insurance risk\n    - American Community Survey (ACS)\n    - NYC Open Data\n    - predictive modeling\n\ndate: last-modified\nbibliography: bibliography.bib\n\nformat:\n  elsevier-pdf:\n    keep-tex: true\n    citation-style: authoryear \n---\n\n## Introduction\n\nAccurate insurance risk modeling is critical for setting fair premiums, mitigating losses, and ensuring financial stability within the insurance industry \\citep{henckaerts, clemente}. Predicting claim frequency and severity not only supports pricing but also enables insurers to manage portfolio-level risk and optimize resource allocation \\citep{mohamed}.\n\nNew York City (NYC) presents a complex urban environment where traffic risks are shaped by socio-economic factors, dense infrastructure, and scaling dynamics typical of large metropolitan areas \\citep{cabrera, bettencourt}. The availability of open datasets—such as NYC’s Motor Vehicle Collision (MVC) data and socio-economic indicators from the American Community Survey (ACS)—offers a unique opportunity to develop proxy models for insurance claim risk. These data sources provide detailed insights into crash frequency, injury severity, commuting behaviors, and neighborhood-level demographics \\citep{adeniyi, brubacher}.\n\nTraditional actuarial methods, such as Generalized Linear Models (GLMs), have long been the foundation of risk pricing and underwriting due to their interpretability and regulatory acceptance \\citep{henckaerts}. However, GLMs are limited in their ability to capture non-linear relationships and interactions among complex predictors like socio-economic factors, urban infrastructure, and driving behavior \\citep{clemente}. These limitations are particularly pronounced in urban contexts, where crash risk is shaped by heterogeneous population dynamics and localized factors \\citep{cabrera, brubacher}.\n\nThere is a growing need for data-driven approaches that can flexibly incorporate diverse predictors—such as open crash data and socio-economic variables—while addressing the complex temporal and spatial patterns of accidents highlighted in recent reviews \\citep{grigorev, behboudi}. Recent studies and systematic reviews confirm that machine learning (ML) methods, particularly ensemble models like Gradient Boosting Machines (GBMs), XGBoost, and LightGBM, outperform traditional GLMs for predicting both claim frequency and severity \\citep{clemente, mohamed, behboudi}. These models are capable of handling mixed data types (categorical and continuous) and capturing complex feature interactions that linear models often miss.\n\nTo address the interpretability challenge of “black box” ML models, SHAP (SHapley Additive exPlanations) offers a principled framework for feature attribution, allowing insurers and policymakers to understand both global feature importance and instance-level predictions \\citep{lundberg, dong, ning}. This combination of high-performance prediction and explainability provides a strong foundation for modern risk modeling, as demonstrated in other domains such as maritime safety where interpretable models like SHAP have been applied \\citep{kim}.\n\nDespite the growing body of work applying ML to insurance modeling, few studies integrate publicly available crash data with socio-economic indicators to model claim-related risks. Most research remains limited to proprietary policyholder data \\citep{henckaerts, mohamed}, while systematic reviews highlight that few studies combine open crash data with socio-economic indicators in insurance modeling \\citep{ali, behboudi}.\n\nThis study aims to integrate ACS socio-economic features with NYC MVC crash data to develop an explainable gradient boosting framework. The ultimate goal is to identify key socio-economic and transportation predictors that drive claim frequency and severity proxies, offering insights for both insurers and urban policymakers.\n\nThe remainder of this paper is organized as follows: Section 2 reviews prior work on machine learning in insurance risk modeling, crash and socio-economic data, geospatial analytics, model explainability, and literature gaps; Section 3 details the data sources, key metrics, modeling approach, and SHAP-based explainability; Section 4 reports the results including model performance, feature importance, and geospatial patterns; Section 5 discusses the findings in relation to existing research and industry applications; and Section 6 concludes with key contributions, limitations, and directions for future research.\n\n## Related Work\n\n### **Machine Learning in Insurance Risk Modeling**\n\nThe transition from traditional actuarial models such as Generalized Linear Models (GLMs) to machine learning (ML) approaches has marked a significant evolution in insurance risk modeling. GLMs have historically served as the backbone for pricing and claim prediction due to their interpretability and regulatory acceptance. However, they are limited by their linearity and inability to naturally capture complex interactions and nonlinear relationships among predictors, such as driver demographics, vehicle characteristics, socio-economic factors, and driving behavior. As \\citet{clemente} note, while GLMs remain effective for modeling claim severity with smaller and noisier datasets, they often underperform compared to ensemble methods when modeling claim frequency, where nonlinearities and heterogeneous risk patterns are prevalent. Similarly, \\citet{jonkheijm} demonstrated that tree-based models, especially XGBoost, substantially improved predictive accuracy over linear regression, particularly when incorporating both actuarial features (e.g., policyholder age, vehicle value) and behavioral indicators.\n\nRecent studies have validated the predictive superiority of ML methods—such as random forests, gradient boosting machines (GBM), and neural networks—over traditional actuarial models. Gradient boosting methods, such as XGBoost and LightGBM, have emerged as particularly effective tools in auto insurance risk modeling \\citep{henckaerts}. Their iterative boosting framework enables them to handle mixed data types (categorical and continuous) and capture intricate patterns that GLMs and single decision trees may miss. \\citet{clemente} applied gradient boosting to both claim frequency and severity modeling, demonstrating significant performance gains in frequency prediction over Poisson-based GLMs. Similarly, \\citet{jonkheijm} employed XGBoost for forecasting individual claim amounts, outperforming both regression trees and random forests.\n\n### **Use of Crash and Socio-Economic Data**\n\nCrash data has been widely recognized as a reliable proxy for insurance claim frequency and severity, given the direct link between the occurrence of traffic accidents and subsequent claims filed by policyholders. Studies leveraging police crash reports, telematics, and open transportation datasets consistently demonstrate strong correlations between crash frequency and insurance risk metrics \\citep{takale}. The integration of socio-economic features—including income levels, commuting patterns, vehicle ownership rates, and population density—has been shown to enhance the explanatory power of crash and claim prediction models.\n\nFor example, \\citet{adeniyi} utilized a decade of NYC crash data (2013–2023) to identify key predictors of accident severity—such as unsafe speed, alcohol involvement, and adverse weather—which align closely with the variables insurers use to model claim likelihood. Similarly, \\citet{dong} applied boosting-based ensemble models to traffic injury severity prediction, finding that vehicle type, collision mode, and environmental conditions strongly influenced both injury outcomes and, by extension, potential claim costs. \\citet{brubacher} conducted a geospatial analysis of 10 years of crashes in British Columbia and found that regions with lower income and higher socio-economic deprivation exhibited higher rates of pedestrian crashes, severe injuries, and fatalities, reflecting disparities in road safety linked to infrastructure quality and enforcement intensity. \\citet{cabrera} expanded on this by identifying superlinear scaling of road accidents in urban areas, where higher population densities led to disproportionate increases in crash frequency, especially for minor collisions. These findings are directly relevant for insurers, as they imply that socio-economic and urban structural factors—such as commuting patterns or access to public transit—can serve as proxies for underlying risk exposure.\n\nUrban-focused studies have further illuminated the unique risk dynamics in metropolitan environments like New York City, Chicago, and London, where complex traffic patterns, dense road networks, and high pedestrian activity elevate accident risk. \\citet{adeniyi} analyzed NYC crash data to show how the COVID-19 pandemic altered accident patterns, with fewer total crashes but an increase in injury severity due to higher vehicle speeds on less congested roads. \\citet{feng}, studying UK traffic data, emphasized the value of big data platforms and spatial clustering techniques (e.g., accident hotspot detection) to identify urban risk zones, a concept that parallels insurer efforts to assess region-based risk for underwriting.\n\nCollectively, these studies support the notion that combining crash data with socio-economic indicators offers a powerful means of modeling insurance claim frequency and severity. By integrating open data sources—such as NYC’s Vision Zero crash records and U.S. Census-derived socio-economic attributes—researchers and insurers can capture a more holistic view of driver risk behavior, infrastructure quality, and regional safety disparities.\n\n### **Explainability in Machine Learning Models**\n\nIn high-stakes fields such as insurance pricing, underwriting, and claims management, the interpretability of machine learning (ML) models is not only a technical preference but also a regulatory and business requirement. Insurers must be able to justify rating factors and risk scores to regulators, policyholders, and internal stakeholders. Traditional actuarial models like GLMs are naturally interpretable due to their linear structure and explicit coefficient estimates. However, modern ML models—such as gradient boosting or neural networks—are often criticized as “black boxes,” complicating the explanation of predictions that influence financial decisions or customer premiums. Regulatory frameworks, including the EU’s General Data Protection Regulation (GDPR) and U.S. state-level insurance guidelines, increasingly require transparency in algorithmic decision-making, further amplifying the need for explainable AI (XAI). \\citet{henckaerts} further underscore this, showing that variable importance plots and PDPs can yield actionable insights into driver and policyholder risk factors, blending predictive power with interpretability.\n\nAmong XAI methods, SHAP (SHapley Additive exPlanations) has become the state-of-the-art framework for interpreting complex ML models. Developed by \\citet{lundberg}, SHAP is grounded in cooperative game theory, assigning each feature a Shapley value that quantifies its contribution to individual predictions. Unlike traditional feature importance metrics—such as Gini importance in random forests or split gain in XGBoost—SHAP accounts for both main effects and feature interactions, offering a consistent and additive explanation of how variables drive model outputs.\n\nTools like SHAP allow practitioners to interpret complex models by quantifying the contribution of each variable to the predictions. Studies like \\citet{mohamed} highlight the value of such interpretability when using gradient boosting for pricing and fraud detection, as insurers must justify rating factors for regulatory compliance.\n\nIn the insurance domain, SHAP has been widely applied to interpret models for claims prediction, fraud detection, and risk scoring. \\citet{dong} used SHAP in conjunction with boosting-based models (LightGBM and CatBoost) to analyze the contribution of driver age, vehicle type, and collision type to injury severity predictions, providing insights that aligned with domain expertise. Similarly, \\citet{ning} demonstrated how Shapley Variable Importance Cloud (ShapleyVIC) builds on SHAP principles to assess variable significance with uncertainty intervals, enabling fairer and more transparent risk predictions. These approaches not only improve trust in ML-driven decision-making but also help insurers identify the most actionable risk factors influencing claims.\n\n### **Gaps in the Literature**\n\nWhile machine learning methods—particularly ensemble models like gradient boosting—have gained traction in insurance risk modeling, there is a notable absence of studies that combine socio-economic and crash data for claim risk prediction. Most existing research focuses on proprietary insurance datasets containing policyholder and vehicle information \\citep{clemente, henckaerts, jonkheijm}. However, publicly available crash datasets, such as NYC’s Motor Vehicle Collision (MVC) reports, and socio-economic features from the American Community Survey (ACS) remain underutilized in insurance modeling. This gap limits the development of robust, regionally sensitive models that capture the real-world interaction between driving risk factors (e.g., crash frequency) and socio-economic indicators (e.g., income, commuting patterns, and vehicle ownership rates). By integrating ACS data with urban crash records, it becomes possible to construct granular, location-aware risk models that better reflect variations in driving exposure, infrastructure quality, and neighborhood-level risk factors.\n\n## Materials and Methods\n\n### **Data Sources and Preprocessing**\n\nThis study integrates publicly available crash data from New York City with socio-economic features from the American Community Survey (ACS) to develop a proxy model for insurance claim risk. The data sources and preprocessing steps are designed to replicate key factors used in actuarial risk models while incorporating broader socio-economic and regional variables.\n\n#### Crash Data (Claim Proxies)\n\nCrash data is obtained from the NYC Motor Vehicle Collisions (MVC) Open Data Portal, covering the years 2018–2023. Each record includes details such as crash location, number of injuries and fatalities, vehicle type, and contributing factors (e.g., driver behavior, environmental conditions). These variables are well-documented predictors of both accident severity and insurance claims \\citep{adeniyi, dong}.\n\nCrash frequency was aggregated at the 2020 census tract level and normalized by tract-level population to compute crashes per 1,000 resident. This mentric will replace claim frequency \\citep{brubacher}.\n\n#### Socio-Economic Data (ACS Features)\n\nSocio-economic variables are drawn from the ACS 5-year estimates (2018–2023) at the 2020 census tract level. The variables include demographic composition (e.g., % male, % white, % Black, % Asian, % Hispanic, % foreign-born), age distribution (% under 18, % 18–34, % 35–64, % 65+), and income indicators (median income, % households earning \\<\\$25,000, % households earning \\$25,000–\\$75,000, % below the poverty line). Additional features include median gross rent, housing tenure (% owner- vs. renter-occupied), educational attainment (% with high school diploma, % with bachelor’s or graduate degrees), employment metrics (% in labor force, unemployment rate), and transportation factors (% driving alone, % carpooling, % using public transit, % walking, % biking, % working from home, and commute time distributions). Interaction features poverty × vehicle ownership and unemployment × vehicle ownership were engineered to capture compound effects on risk exposure. These features have been shown to correlate with traffic risk and claim likelihood, as evidenced by \\citet{brubacher} and \\citet{cabrera}, who found that socio-economic deprivation and commuting behaviors strongly influence crash frequency and severity.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: ACS tables used and derived variables.\n\n|ACS    |Description                                          |Derived.Variables                                                                                     |\n|:------|:----------------------------------------------------|:-----------------------------------------------------------------------------------------------------|\n|B01001 |Age and Sex                                          |total_population, male_population, female_population, age_under_18, age_18_34, age_35_64, age_65_plus |\n|B01003 |Total Population                                     |total_population                                                                                      |\n|B08134 |Means of Transportation to Work by Vehicle Occupancy |drive_alone, carpool                                                                                  |\n|B08301 |Means of Transportation to Work                      |public_transit, walk, bike, work_from_home                                                            |\n|B08303 |Travel Time to Work                                  |commute_short, commute_medium, commute_long                                                           |\n|B19001 |Household Income Distribution                        |income_under_25k, income_25k_75k, income_75k_plus                                                     |\n|B19013 |Median Household Income                              |median_income                                                                                         |\n|B25010 |Average Household Size                               |average_household_size                                                                                |\n|B25044 |Tenure by Vehicles Available                         |no_vehicle, one_vehicle, two_plus_vehicles                                                            |\n|C24010 |Occupation by Sex and Median Earnings                |occupation variables (aggregated)                                                                     |\n|C24030 |Industry by Sex and Median Earnings                  |industry variables (aggregated)                                                                       |\n|B15003 |Educational Attainment                               |less_than_hs, hs_diploma, some_college, associates_degree, bachelors_degree, graduate_degree          |\n|B17001 |Poverty Status                                       |below_poverty, above_poverty, poverty_rate                                                            |\n|B02001 |Race                                                 |white_population, black_population, asian_population                                                  |\n|B03002 |Hispanic or Latino Origin by Race                    |hispanic_population                                                                                   |\n|B08201 |Household Size by Vehicles Available                 |vehicle availability (aggregated)                                                                     |\n|B18101 |Sex by Age by Disability Status                      |disability variables (aggregated)                                                                     |\n|B16005 |Nativity by Language Spoken at Home                  |foreign_born                                                                                          |\n|B23025 |Employment Status for Population 16+                 |in_labor_force, employed, unemployed, not_in_labor_force, unemployment_rate                           |\n|B25064 |Median Gross Rent                                    |median_gross_rent                                                                                     |\n|B09005 |Household Type (Families vs Non-families)            |household_type variables                                                                              |\n|B11001 |Household Type by Presence of Children               |household_type_children variables                                                                     |\n\n\n:::\n:::\n\n\n#### Preprocessing Steps\n\nCrash records from the NYC Open Data MVC dataset are cleaned (removing rows with missing or zero coordinates) and spatially joined to 2020 Census Tracts using official census tract shapefiles. Annual summaries of total crashes, injuries, and fatalities are then aggregated by tract and normalized by tract-level population to compute per-capita crash, injury, and fatality rates. The ACS socio-economic data are harmonized to 2020 tract boundaries (via crosswalks for 2018–2019), binned into interpretable categories (e.g., income brackets, age groups, education levels), and converted to percentages of total population where applicable. Interaction features—such as poverty × vehicle ownership and unemployment × vehicle ownership—are engineered to capture compounded socio-economic risk factors.\n\nNo categorical encoding besides `year` or standardization was performed at this stage since all ACS features are already expressed as continuous percentages or numeric values, and gradient boosting models (XGBoost) handle raw scales effectively \\citep{henckaerts}. The resulting integrated dataset combines socio-economic indicators with tract-level crash metrics, allowing us to explore how demographic and transportation characteristics interact with crash patterns to inform insurance claim frequency and severity modeling, filling a gap in the literature where public ACS and crash data are rarely combined \\citep{mohamed, jonkheijm}.\n\n### **Key Metrics**\n\nTo model insurance risk in the absence of proprietary claims data, publicly available crash data is used as a proxy for both claim frequency and severity, a practice supported by prior research that links traffic accidents directly to insurance losses \\citep{adeniyi, dong}.\n\nOur primary risk metric, crash_rate_per_1000, measures the number of crashes per 1,000 residents in each census tract-year. This population-adjusted rate follows the methodology of studies that normalize crash counts by population to ensure fair comparisons of relative risk across areas with varying exposure levels \\citep{brubacher, cabrera}.\n\nThese crash metrics are modeled alongside the socio-economic and transportation variables detailed in Table 2, which include demographic distributions (e.g., % white, % Hispanic), income and poverty indicators (e.g., median income, poverty rate), commuting and transportation patterns (e.g., % public transit use, % walk, % bike), and engineered interaction features (e.g., poverty × vehicle ownership). Together, these variables allow the model to capture both the exposure risk (frequency) and potential cost severity of accidents, aligning with the frameworks used in both insurance \\citep{clemente, henckaerts} and traffic safety research \\citep{dong}.\n\nTo reduce multicollinearity and improve model performance, we removed a subset of socio-economic and transportation variables that were highly correlated with other features. Measures of poverty level and population above the poverty line, as well as employment and unemployment percentages, were closely tied to broader income and labor force indicators already included in the model, creating redundancy without improving predictive power. Similarly, metrics describing commuting alone by car and the distribution of vehicle ownership (households with no vehicles, one vehicle, or multiple vehicles) were strongly interrelated due to their compositional nature. We also excluded the percentage of female residents because of its near-perfect correlation with the male share of the population, and the share of high-income households (earning above $75,000), which closely overlapped with median income levels. \n\n### **Modeling Approach**\n\nTo model the relationship between socio-economic characteristics and crash risk, we implemented a single gradient boosting framework using XGBoost, rather than multiple boosting algorithms. Gradient boosting was selected because of its proven ability to model complex, non-linear interactions and handle heterogeneous input variables (for this project, percentages, continuous income values, and engineered features) without requiring variable standardization or heavy preprocessing \\citep{clemente, mohamed}.\n\nXGBoost is chosen for its strong track record in insurance risk modeling and interpretability when combined with SHAP \\citep{dong}. This model selection aligns with studies comparing boosting frameworks for both frequency-severity modeling \\citep{henckaerts} and urban crash prediction \\citep{adeniyi}.\n\nTo optimize model performance, we performed hyperparameter tuning through exploratory grid searches rather than using automated Bayesian optimization frameworks like Optuna. The tuning process focused on key parameters such as `max_depth`, `learning_rate`, `subsample`, and `colsample_bytree`, which significantly influence the complexity and generalization ability of gradient boosting models. This approach is supported by prior research showing that systematic hyperparameter optimization significantly improves boosting model accuracy \\citep{liu}.\n\nEach configuration was evaluated using spatial cross-validation at the borough level on the training data to balance bias and variance, ensuring that the model captured meaningful patterns without overfitting or overgeneralizing across geography. This iterative approach, while more manual than advanced optimization tools, was sufficient for our dataset size and feature set, yielding robust improvements in predictive accuracy. Model performance was then validated on the holdout test set using RMSE, MAE, and R² metrics.\n\n#### Explainability\n\nGiven the regulatory and operational need for transparent, explainable models in insurance \\citep{henckaerts, lundberg}, we employ SHAP (SHapley Additive exPlanations) for both global and local feature analysis. SHAP values are aggregated across the dataset to quantify overall feature importance, revealing which socio-economic and crash-related variables most influence predicted claim frequency and severity.\n\n## Results\n\n### **Hyperperameter Tuning**\n\nTo enhance the predictive accuracy and generalization capability of the XGBoost model, we performed systematic hyperparameter tuning. A series of grid-based experiments were conducted to explore the influence of tree depth, learning rate, regularization terms, and sampling ratios on model performance. The final configuration represents a balance between model complexity and overfitting risk, as determined by performance on the training and validation subsets.\n\n| Action | Parameter  | Value     |\n|---------|-----------|-----------|\n| Learning Rate | `eta`  | 1.549545  |\n| Tree Depth | `max_depth`  | 4 |\n| `min_child_weight` | 3 |\n| Reduce Randomness | `subsample` | 0.5583975 |\n| Reduce Randomness | `colsample_bytree` | 0.8797697 |\n| Regularization | `gamma` | 3.35839 |\n| Regularization | `lambda` | 6.131609 |\n| Regularization | `alpha` | 2.805485 |\n\n: Optimal Parameters as per Optuna\n\nA tree depth of 4 means the model only splits features a few times before making predictions. This suggests that the relationships in your data are not overly complex, and deeper trees could lead to overfitting. The socio-economic and crash-rate features capture patterns that can be learned with relatively few decision boundaries.\n\nThis high learning rate is unusually high compared to common XGBoost defaults (0.01–0.3), indicating the model is taking larger steps while fitting each tree. This could imply that the signal-to-noise ratio in your data is high—each tree provides strong improvements—or that the dataset is relatively small (13,518 rows), allowing a faster convergence without needing a very gradual learning rate. However, high eta combined with shallow trees requires careful monitoring for overfitting, which the regularization terms help mitigate.\n\nThe Subsampling Ratios (`subsample = 0.56`, `colsample_bytree = 0.88`) show model uses just over half of the rows for each boosting iteration and nearly all features. This randomness prevents any one subset of data from dominating the model and improves generalization. It suggests your dataset has sufficient size and diversity to benefit from row sampling, but not so many redundant features that aggressive column sampling is needed.\n\nRegularization Parameters (`lambda = 6.13`, `alpha = 2.81`, `gamma = 3`.36) are relatively strong regularization values, indicating the model needed constraints to avoid overfitting. In practice, this means there is enough correlation and redundancy among features (e.g., multiple income and vehicle ownership metrics) that the model benefits from being penalized for complex splits or large feature weights.\n\nOverall, these values suggest that the data contains strong, interpretable signals, but also some multicollinearity and noise, which the model combats with regularization and shallow trees. The model prioritizes broad, stable patterns (e.g., effects of median income, public transit usage, and poverty rate) rather than deep, highly localized interactions.\n\n### **Model Performance and Diagnostics**\n\nThe XGBoost model achieved robust predictive performance on the holdout test set, with the following metrics:\\\n\n| Metric  | Score     |\n|---------|-----------|\n| RMSE  | 1.549545  |\n| MAE   | 0.8372956 |\n| $R^2$ | 0.2595503 |\n\n: Model Evaluation Metrics\n\nThe XGBoost model’s evaluation metrics suggest moderate predictive power with stable error bounds on the holdout test set. An RMSE of 1.55 indicates that the model’s predicted crash rates deviate, on average, by roughly 1.5 crashes per 1,000 residents from observed values, with MAE (0.84) confirming that most prediction errors are below 1 crash per 1,000 residents. While the R2=0.26R2=0.26 shows that the model explains about 26% of the variance in crash rates across census tracts, this is consistent with the high degree of randomness and unobserved factors (e.g., driver behavior, weather) inherent in crash data.\n\nThese metrics reflect the trade-offs embedded in the tuned hyperparameters. The shallow max_depth (4) and strong regularization (λ=6.13λ=6.13, α=2.81α=2.81, γ=3.36γ=3.36) prevent the model from overfitting, but also limit its ability to capture highly localized or complex patterns. The high learning rate (eta = 1.55) ensures faster convergence and emphasizes broader trends rather than granular noise. Together, these settings produce a model that prioritizes generalizable patterns over perfectly fitting outliers, explaining why errors remain stable (as seen in the low MAE) even if the R2R2 is not exceptionally high.\n\n#### **Examination of the Residuals**\n\nThe predicted vs. actual values plot shows that the model captures the general trend of observed crash rates across census tracts, with most predictions clustering closely around the 45-degree reference line. While a slight underestimation is evident for the highest crash-rate tracts, this is typical for gradient boosting models where extreme outliers are smoothed during ensemble averaging.\n\n![Predicted verses Actual Values on the Test Set](plots/predicted_vs_actual_values_plot.png)\n\nThe residual density plot indicates residuals are centered near zero with a narrow peak, suggesting minimal systemic bias.\n\n![Residual Density Plot](plots/residual_density_plot.png)\n\nThe residuals vs. predicted values plot shows a random scatter around zero, with no strong patterns of heteroskedasticity or underfitting, although a few outlier tracts exhibit residuals above ±10, likely due to unique local conditions not captured by socio-economic predictors.\n\n![Residuals vs Predicted Values](plots/resisuals_vs_predicted_values_plot.png)\n\n![Global Feature Importance with SHAP](plots/resisuals_vs_predicted_values_plot.png)\n\n### **Global Feature Importance (SHAP)**\n\nThe SHAP summary plot (Figure 5) highlights the most influential features on crash risk predictions. The top 10 variables, in order of importance, are:\n\n#### Post-Pandemic Indicator\n\nThe post_pandemic variableshows a marked upward shift in predicted crash rates from 2020 onward, consistent with observed pandemic-era changes in traffic dynamics (e.g., lower congestion but higher speeds). This confirms that the temporal dimension significantly influences crash risk beyond static socio-economic factors.\n\n#### Aging Population\n\nThe PDP suggests that areas with a moderate share of elderly residents (10–20%) have slightly lower crash risks, potentially due to lower driving exposure. However, beyond 20%, predicted crash risk rises, indicating that vulnerable road users like seniorsmay increase the severity of crashes when incidents occur.\n\n#### High School Graduate Population\n\nFor percent of the population with a high school diploma (but no further education), the PDP exhibits a U-shaped relationship: tracts with either very low or very high shares of residents holding a high school diploma are associated with higher crash risk. This suggests that mid-level education attainment may correlate with safer commuting patterns or less risky behavior.\n\n#### Median Gross Rent\n\nMedian gross rent displays a positive gradient: tracts with higher rents—often denser and more urbanized—show higher crash rates. This likely reflects greater vehicle-pedestrian interactions and traffic intensity in high-rent urban zones.\n\n#### Working Population\n\nThe PDP for percentage of the population in the workforce indicates that crash risk peaks around 60–70% labor force participation. Lower participation areas may have fewer commuters, while areas with higher participation rates may experience higher traffic volumes.\n\n#### Poverty Rate x Vehicle Ownership Interaction\n\nTh variable marking the interaction of vehicle ownership with poverty rate shows that high poverty rates combined with high vehicle ownership strongly elevate crash risk. This finding suggests that economically vulnerable drivers may face both infrastructure and behavioral risks.\n\n![Figure X: Multi-Tree Plot](plots/multi_tree_plot.png)\n\n## Discussion\n\nThe results of our gradient boosting model underscore both the potential and the limitations of integrating socio-economic and transportation indicators into auto insurance risk modeling. Although the model’s R² value of approximately 0.26 indicates that it explains just over one-quarter of the variance in crash rates across New York City census tracts, this is a meaningful achievement considering the inherent randomness of crash events and the absence of individual-level data on drivers and vehicles. Auto collisions are influenced by many unobserved factors—such as momentary driver behavior, local weather conditions, and road design—that cannot be captured through aggregated socio-demographic measures alone. Despite these constraints, the model’s relatively low mean absolute error (0.84 crashes per 1,000 residents) suggests that it has successfully captured consistent, broad patterns in crash risk that align with socio-economic disparities and urban traffic dynamics.\n\nThe SHAP analysis and multi-tree plot reveal that the most influential predictors are not strictly transportation variables but rather socio-economic indicators that shape exposure and vulnerability. The post-pandemic indicator emerges as the single strongest factor, reflecting the profound shift in traffic patterns since 2020, when less congestion but higher average speeds increased crash severity. This temporal variable, acting as a structural change marker, underscores how risk is not static and can be dramatically influenced by societal events. Other dominant features include the percentage of the population aged 65 and older, which is associated with heightened crash severity likely due to the increased vulnerability of older pedestrians and drivers. The model suggests a non-linear relationship: neighborhoods with a moderate share of elderly residents (10–20%) have slightly lower risk—perhaps due to reduced driving exposure—while higher concentrations of elderly populations increase risk due to physical fragility and slower response times during collisions.\n\nHousing and economic variables also feature prominently. Median gross rent is positively correlated with crash rates, suggesting that denser, higher-cost urban areas, with more vehicle-pedestrian interactions and complex traffic flows, have elevated risk levels. Similarly, labor force participation peaks as a predictor around 60–70%, reflecting that areas with higher commuter activity experience more traffic and thus more collisions. The inclusion of income distribution metrics—particularly the share of households earning under $25,000 and between $25,000–$75,000—highlights how economic vulnerability and mid-range income commuting patterns interact to shape risk exposure.\n\nOne of the most striking findings is the role of poverty × vehicle ownership interaction, which appears consistently in the multi-tree plot. Areas with both high poverty rates and high vehicle availability show notably higher crash risks, likely due to a combination of older vehicles, reduced access to safety infrastructure, and potentially riskier driving environments. This aligns with prior research linking socio-economic deprivation to both higher accident rates and more severe outcomes due to disparities in road safety infrastructure and enforcement intensity.\n\nFrom a social risk modeling perspective, these results are significant. The SHAP-derived importance of variables like percent of the population walking or biking, public transit use, and commute time reflects how transportation mode choice is strongly tied to risk exposure. For example, tracts with higher walking or biking shares—especially when combined with high rents or dense populations—are more likely to see pedestrian or cyclist-involved accidents. Similarly, higher public transit usage can act as both a risk mitigator (reducing car volume) and a risk amplifier in areas with heavy pedestrian traffic near transit hubs.\n\nWhile the model demonstrates that neighborhood-level demographic and economic factors can act as strong proxies for crash risk, it also highlights critical limitations for deployment in insurance pricing. The moderate R² indicates that a significant portion of risk remains unaccounted for, largely due to unobserved individual-level factors such as driver age, prior claims, and vehicle safety features. Moreover, the use of variables like income, race, or foreign-born population—though statistically predictive—would be highly problematic if directly incorporated into premium calculations due to both legal prohibitions (e.g., anti-discrimination laws) and ethical concerns. These variables risk proxy discrimination, where protected classes are indirectly penalized through correlated socio-economic attributes.\n\nThe model answers our primary research question—whether publicly available socio-economic and crash data can be combined to model geographic risk—and the answer is a qualified yes. It shows that these factors can explain spatial patterns of crashes and provide insurers or policymakers with macro-level risk insights. However, the model cannot, and should not, be used as-is for individual risk assessment. It is better suited for regional portfolio analysis, identifying high-risk neighborhoods for targeted safety interventions, or supplementing traditional actuarial models rather than replacing them.\n\nMoving forward, future research should focus on enhancing the model’s granularity and fairness. Incorporating telematics data, which captures real-time driving behavior (speeding, braking, distance driven), could greatly increase predictive accuracy while avoiding over-reliance on socio-economic proxies. Similarly, integrating temporal modeling techniques—such as time-series gradient boosting or hybrid approaches with recurrent neural networks—would enable the model to capture seasonal and event-driven variations in crash risk. Additionally, fairness-aware machine learning techniques could be applied to mitigate the risk of socio-economic bias while maintaining predictive performance.\n\n## Conclusions and Future Work\n\nThis research demonstrates that gradient boosting, combined with socio-economic and crash data, can provide interpretable, data-driven insights into auto insurance risk patterns in NYC. By identifying key drivers of crash risk—such as post-pandemic shifts, commuting intensity, and socio-economic vulnerability—the model offers a foundation for both urban safety planning and high-level risk assessment.\n\nYet, the study’s findings also underscore the limitations of using aggregated, public data for underwriting. While the model captures broad trends, it lacks the precision, granularity, and fairness safeguards required for production-level insurance applications. Therefore, the model is best suited as a complementary tool for insurers, providing neighborhood-level risk insights or supporting reinsurance and portfolio management rather than individual pricing.\n\nFuture research should focus on three fronts: (1) integrating behavioral data, such as telematics, to bridge the gap between macro-level socio-economic patterns and micro-level driving behavior; (2) developing fairness-aware modeling approaches to mitigate bias from socio-economic proxies; and (3) exploring temporal extensions that incorporate evolving risk factors, including post-pandemic traffic patterns and climate-related hazards. These directions will help transition from descriptive social risk modeling to actionable, ethically sound insurance applications.\n\n## Appendix A: Variables Modeled\n\n::: {.cell tbl-cap='Table 2: Key variables, descriptions, and transformations in the final dataset.'}\n::: {.cell-output-display}\n\n\nTable: Table 2: Key variables, descriptions, and transformations in the final dataset.\n\n|Variable       |Description                          |Type                                                    |Transformation  |\n|:--------------|:------------------------------------|:-------------------------------------------------------|:---------------|\n|Demographic    |pct_male_population                  |Men                                                     |Percentage      |\n|Demographic    |pct_white_population                 |Identifying as white                                    |Percentage      |\n|Demographic    |pct_black_population                 |Identifying as black                                    |Percentage      |\n|Demographic    |pct_asian_population                 |Identifying as Asian                                    |Percentage      |\n|Demographic    |pct_hispanic_population              |Identifying as Hispanic/Latino                          |Percentage      |\n|Demographic    |pct_foreign_born                     |Foreign-born                                            |Percentage      |\n|Age            |pct_age_under_18                     |Under 18                                                |Percentage      |\n|Age            |pct_age_18_34                        |Aged 18-34                                              |Percentage      |\n|Age            |pct_age_35_64                        |Aged 35-64                                              |Percentage      |\n|Age            |pct_age_65_plus                      |Aged 65 and above                                       |Percentage      |\n|Income/Poverty |median_income                        |Median household income (inflation-adjusted)            |Raw value (USD) |\n|Income/Poverty |pct_income_under_25k                 |Households earning less than $25,000                    |Percentage      |\n|Income/Poverty |pct_income_25k_75k                   |Households earning $25,000-$75,000                      |Percentage      |\n|Income/Poverty |pct_below_poverty                    |Below the poverty line                                  |Percentage      |\n|Housing        |median_gross_rent                    |Median gross rent (USD)                                 |Raw value (USD) |\n|Housing        |pct_owner_occupied                   |Owner-occupied housing units                            |Percentage      |\n|Housing        |pct_renter_occupied                  |Renter-occupied housing units                           |Percentage      |\n|Education      |pct_less_than_hs                     |Less than high school education                         |Percentage      |\n|Education      |pct_hs_diploma                       |High school diploma                                     |Percentage      |\n|Education      |pct_some_college                     |Some college education                                  |Percentage      |\n|Education      |pct_associates_degree                |Associate's degree                                      |Percentage      |\n|Education      |pct_bachelors_degree                 |Bachelor's degree                                       |Percentage      |\n|Education      |pct_graduate_degree                  |Graduate or professional degree                         |Percentage      |\n|Employment     |pct_in_labor_force                   |In the labor force                                      |Percentage      |\n|Employment     |unemployment_rate                    |Unemployment rate                                       |Percentage      |\n|Transport      |pct_commute_short                    |Commute under 15 minutes                                |Percentage      |\n|Transport      |pct_commute_medium                   |Commute between 15-30 minutes                           |Percentage      |\n|Transport      |pct_commute_long                     |Commute longer than 30 minutes                          |Percentage      |\n|Transport      |pct_carpool                          |By carpool                                              |Percentage      |\n|Transport      |pct_public_transit                   |By public transit                                       |Percentage      |\n|Transport      |pct_walk                             |By walking                                              |Percentage      |\n|Transport      |pct_bike                             |By biking                                               |Percentage      |\n|Transport      |pct_work_from_home                   |Working from home                                       |Percentage      |\n|Transport      |pct_vehicle                          |Owns a vehicle                                          |Percentage      |\n|Engineered     |post_pandemic                        |Post-pandemic indicator (1 = 2020 and later)            |Binary          |\n|Engineered     |poverty_vehicle\n    _interaction      |Interaction term: poverty rate × vehicle ownership      |Interaction     |\n|Engineered     |unemployment_vehicle\n    _interaction |Interaction term: unemployment rate × vehicle ownership |Interaction     |\n|Year           |year2018                             |Year dummy: 2018                                        |Indicator       |\n|Year           |year2019                             |Year dummy: 2019                                        |Indicator       |\n|Year           |year2020                             |Year dummy: 2020                                        |Indicator       |\n|Year           |year2021                             |Year dummy: 2021                                        |Indicator       |\n|Year           |year2022                             |Year dummy: 2022                                        |Indicator       |\n|Year           |year2023                             |Year dummy: 2023                                        |Indicator       |\n\n\n:::\n:::\n\n\n## References",
    "supporting": [
      "report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}